apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-multi
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - env: dev
        - env: stage
  template:
    metadata:
      name: 'myapp-{{env}}'
      labels:
        env: '{{env}}'
    spec:
      project: production
      source:
        repoURL: https://github.com/Stalker1301981-alt/argocd-demo.git
        targetRevision: HEAD
        path: helm-chart
        helm:
          valueFiles:
          - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
